services:
  web:
    build: .
    env_file:
      - config/config.env
    ports:
      - "7540:7540"
    volumes:
      - .:/usr/src/app
    command: go run cmd/main.go
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER : 'user'
      POSTGRES_PASSWORD : 'password'
      POSTGRES_DB : 'wallet_db'
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis_container
    environment:
      REDIS_PASSWORD : "password"
    ports:
      - "6379:6379"
    volumes:
      - ./data/redisdata:/data

volumes:
  postgres-db:
